writing 1.md

diff --git a/shell_scripts/inpath b/shell_scripts/inpath
--- a/shell_scripts/inpath
+++ b/shell_scripts/inpath
@@ -8,7 +8,7 @@ in_path()
     # 만약 그렇지 않으면 1을 리턴한다. 이것을 일시적으로 IFS(내부 필드 분리 기호)를 수정하지만,
     # 완료 후 복원한다.
 
-    cmd=$1		ourpath=$2	result=1
+    cmd=$1		  ourpath=$2	result=1
     oldIFS=$IFS	IFS=":"
 
     for directory in “$ourpath”
@@ -24,29 +24,29 @@ in_path()
 
   checkForCmdInPath()
   {
-      var=$1
+    var=$1
       
-      if [ "$var" != "" ] ; then
-        if [ "${var:0:1}" = "/" ] ; then
-          if [ ! -x $var ] ; then
-        return 1
-          fi
-        elif ! in_path $var "$PATH" ; then
-          return 2
+    if [ "$var" != "" ] ; then
+      if [ "${var:0:1}" = "/" ] ; then
+        if [ ! -x $var ] ; then
+          return 1
         fi
+      elif ! in_path $var "$PATH" ; then
+        return 2
       fi
+    fi
 }
 
-if [ $# -ne 1 ] ; then
-  echo "Usage: $0 command" >&2
-  exit 1
-fi
+# if [ $# -ne 1 ] ; then
+#   echo "Usage: $0 command" >&2
+#   exit 1
+# fi
 
-checkForCmdInPath "$1"
-case $? in
-  0 ) echo "$1 found in PATH"                ;; # 이거 안되요 ㅠㅠ
-  1 ) echo "$1 not found or not executable"  ;;
-  2 ) echo "$1 not found in PATH"            ;;
-esac
+# checkForCmdInPath "$1"
+# case $? in
+#   0 ) echo "$1 found in PATH"                ;; # 이거 안되요 ㅠㅠ
+#   1 ) echo "$1 not found or not executable"  ;;
+#   2 ) echo "$1 not found in PATH"            ;;
+# esac
 
-exit 0
+# exit 0
